export let callingCodes = {
    'ukraine': '380',
    'afghanistan': '93',
    'albania': '355',
    'algeria': '213',
    'belgium': '32',
    'poland': '48',
    'iran': '98',
    'germany': '49',
    'finland': '358',
    'australia': '61',
    'turkey': '90',
    'switzerland': '41',
    'new zealand': '64',
    'spain': '34',
    'norway': '47',
    'denmark': '45',
    'united states': '1',
    'canada': '1',
    'france': '33',
    'netherlands': '31'
}